### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#146]
I'm getting bored of polysemy! All of the hard work has been done, and now it's just maintenance. To that end, I'd like to get everything polished for a v1 release, and then put this on the backburner until GHC 8.10 comes out and we (probably) need to worry about the performance story again.

# For Sures

- [x] weird error messages with no commas (#74) --- should be trivial now with the new error handling machinery
- [x] haddock is broken for external deps (#98) --- trivial, just let hackage build the haddocks
- [x] fix bad error messages when things don't typecheck (#136) --- probably pretty involved
- [ ] document the semantics behind relative order of effects (#127) --- easy, just takes some time
- [x] add `embed :: (LastMember IO r, MonadIO m) => (forall a. m a -> IO a) -> Sem (Lift m ': r) a -> Sem r a` (#137) --- super trivial, it's already written
- [ ] better UX around `Lift` (#142) --- easy
- [ ] trawl through the common libraries and make sure we have all of the combinators we need for real life code
- [ ] make sure the type variables are in the most useful order for everything exposed by the library (#156)
- [ ] come up with a consistent naming scheme across all effects; right now it's a damn mess

# Someday Maybes

- [ ] Move the polysemy-zoo/Absorption machinery into polysemy proper
- [x] Solve the bad errors from ambiguoustypes (#55) --- are there any stuckness properties we can exploit for this?
- [x] Change the type of `runBatchOutput` (#112)

**Comment by ocharles** [comment]
There is still the problem that `data Effect m a where E :: m a -> Effect m (f a)` can't be written, but I guess we're accepting this as "not possible"? I demonstrated how it could be done in https://gist.github.com/ocharles/1ff937a57aa45fd53e0ab26653781085, just curious if that's something we want to explore or not.

**Comment by isovector** [comment]
@ocharles to clarify, you mean for a statically known compositon-of-all-state `f`?

**Comment by ocharles** [comment]
I should have written  `data Effect m a where E :: m a -> E m (F a)`. Basically, if an effect needs to run an `m a` and store the `a` in some container of it's choice (`F`, e.g., `Async`), such a thing cannot be safely written in `polysemy` today (because you need to know that only `Identity` is weaved through).

**Comment by isovector** [comment]
I'm going to mark that as out of scope. Just deal with the damn `Maybe`! ;)

**Comment by TheMatten** [comment]
> make sure the type variables are in the most useful order for everything exposed by the library

So put `forall` on every part of API to explicitly mark order of arguments?

**Comment by isovector** [comment]
Not necessarily `forall` them if they're already in a good shape, but eg #131 is a good change. I'm sure there are others like it in the codebase!

**Comment by isovector** [comment]
Just going to use the milestone tracker in GH instead of this issue.
